### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by alexws54tk** [bobwya/gentoo-wine-esync#1]
How to use this with Gentoo Portage patches system?

Best regards,
alex.

**Comment by bobwya** [comment]
This repository is intended for _internal use only_, for use with my Overlay **::bobwya** **app-emulation/wine-vanilla** and **app-emulation/wine-staging** packages. Hence why the documentation is a bit sparse. See: [Github: bobwya/bobwya Wiki: Wine Packages](https://github.com/bobwya/bobwya/wiki/Wine-Packages).

If you don't mind jumping through some hoops and are wedded to the stock Gentoo or ::**wine** Wine packages... Then it's not too hard to apply one Wine version specific patchset from (either):

    wine-staging/
    wine-vanilla/

in this repository, as [Gentoo User patch](https://wiki.gentoo.org/wiki//etc/portage/patches)(es).

The patchsets under:

    wine-staging/
    wine-vanilla/

are sorted by the first Wine commit that they apply to. I'd suggest taking a look at the **wine_eapply_esync_patchset** in the ::**bobwya** Overlay [wine.eclass](https://github.com/bobwya/bobwya/blob/master/eclass/wine.eclass) file. Should make things a little clearer! :-)

I'd also warn that Zebediah has categorically stated that he is not terribly interested in enhancing the compatibility of **wine-esync** (although he is rebasing it as necessary, so it's kind of on "life-support" only). I find **wine-esync** tends to lead to Wine deadlocks, with core applications like the Windows Steam Client... So it's not that beneficial for my use cases... Which was especially annoying after I spent hours writing scripts to manually clean up the patches (to ensure they apply cleanly) and then "squash" them into a more compact patchset (i.e. discarding the revision history).

But hey don't let me dissuade you from trying it though! At least one Gentoo user has reported some success on IRC (I can't remember what game he/she was testing). Also I've backported the patchsets to Wine / Wine Staging 3.0(+) - so you may find earlier Wine versions work more successfully...

Bob

**Comment by alexws54tk** [comment]
Thank you very much for this copletely answer. I add your overlay and install Wine Packages.
At now, I installing some games trough Lutris.

Best regards,
alex

**Comment by funghetto** [comment]
> I find **wine-esync** tends to lead to Wine deadlocks, with core applications like the Windows Steam Client... So it's not that beneficial for my use cases... Which was especially annoying after I spent hours writing scripts to manually clean up the patches (to ensure they apply cleanly) and then "squash" them into a more compact patchset (i.e. discarding the revision history).

Why doesn't wine-esync from TkGlitch seem to suffer from these deadlocks?

**Comment by bobwya** [comment]
@funghetto 

Sorry about the delay with this. It's quite time consuming to pin down the errors, in my version of the patchsets (there are so many patches), so I didn't want to half arse this process.

Anyway you should be good to go now! :+1:

Bob
